# Generated by Django 5.0.4 on 2024-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
