# Generated by Django 5.0.4 on 2024-06-25 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
