# Generated by Django 5.0.4 on 2024-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_livros_emprestado_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
