# Generated by Django 5.0.4 on 2025-01-17 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 21, 10, 6, 489796)),
        ),
    ]
